<a href="https://colab.research.google.com/github/sandeep4055/pytorch_practise/blob/main/Pytorch_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

1.13.1+cu116


# Creating Tensor

In [4]:
# sacler where ndim=0
scaler = torch.tensor(4)
scaler,scaler.ndim

(tensor(4), 0)

In [5]:
type(scaler)

torch.Tensor

In [6]:
# Get the Python number within a tensor (only works with one-element tensors)
scaler.item()

4

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
# Check shape of vector
vector.shape

torch.Size([2])

In [10]:
# Matrix
MATRIX = torch.tensor([[7, 8,2], 
                       [9, 10,6]])
MATRIX

tensor([[ 7,  8,  2],
        [ 9, 10,  6]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 3])

In [13]:
Tensor = torch.tensor([
    [
        [1,2,5],[2,3,4],[4,6,7]
     ],
     [
        [1,2,3],[2,3,4],[4,6,7]
     ]
     ])

print(f"Tensor {Tensor}")
print(f"Tesnor shape {Tensor.shape}")

Tensor tensor([[[1, 2, 5],
         [2, 3, 4],
         [4, 6, 7]],

        [[1, 2, 3],
         [2, 3, 4],
         [4, 6, 7]]])
Tesnor shape torch.Size([2, 3, 3])


In [14]:
# Slicing 3d tensor
# Tensordim,rows, columns
Tensor[:1,:2,:-1]

tensor([[[1, 2],
         [2, 3]]])

In [15]:
Tensor.is_cuda

False

In [16]:
Random_tensor = torch.rand(size=(3,3,4))
Random_tensor

tensor([[[0.3324, 0.6191, 0.5227, 0.3543],
         [0.3479, 0.0779, 0.3892, 0.7958],
         [0.4267, 0.7451, 0.6094, 0.1190]],

        [[0.6338, 0.0987, 0.1724, 0.7757],
         [0.4853, 0.0340, 0.7564, 0.8360],
         [0.5769, 0.4287, 0.9463, 0.8909]],

        [[0.8329, 0.7445, 0.2977, 0.4753],
         [0.3835, 0.8691, 0.4312, 0.0063],
         [0.0370, 0.8405, 0.1028, 0.4600]]])

In [17]:
Random_tensor.dtype

torch.float32

In [18]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))

random_image_size_tensor 

tensor([[[0.6043, 0.8350, 0.9850],
         [0.0649, 0.7340, 0.4230],
         [0.3841, 0.7984, 0.8015],
         ...,
         [0.5939, 0.7712, 0.1468],
         [0.0043, 0.9645, 0.5171],
         [0.0277, 0.1616, 0.1726]],

        [[0.0516, 0.7005, 0.5518],
         [0.6014, 0.5052, 0.9036],
         [0.4659, 0.5839, 0.4241],
         ...,
         [0.5475, 0.0828, 0.6624],
         [0.0087, 0.0551, 0.9287],
         [0.4311, 0.7765, 0.6748]],

        [[0.5433, 0.4224, 0.2057],
         [0.9547, 0.0995, 0.5935],
         [0.6520, 0.6653, 0.8931],
         ...,
         [0.3596, 0.1572, 0.1545],
         [0.9782, 0.8605, 0.3593],
         [0.4315, 0.4365, 0.7863]],

        ...,

        [[0.8139, 0.8318, 0.5405],
         [0.7569, 0.1867, 0.1307],
         [0.2111, 0.1514, 0.4405],
         ...,
         [0.7995, 0.7417, 0.8048],
         [0.7070, 0.8547, 0.1057],
         [0.8012, 0.1748, 0.5942]],

        [[0.9370, 0.4226, 0.9148],
         [0.0331, 0.7826, 0.8101],
         [0.

In [19]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]), torch.float32)

In [20]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Aside from shape issues (tensor shapes don't match up), two of the other most common issues you'll come across in PyTorch are datatype and device issues.

For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).

In [21]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.6730, 0.1916, 0.7784, 0.0249],
        [0.7457, 0.4578, 0.2049, 0.8304],
        [0.5071, 0.5793, 0.1036, 0.7128]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [22]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [23]:
tensor * 10

tensor([10, 20, 30])

In [24]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [25]:
tensor.matmul(tensor)

tensor(14)

In [26]:
tensor = torch.tensor([[1, 2, 3]])
tensor.matmul(torch.tensor([[3],[2],[1]]))

tensor([[10]])

In [27]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ torch.tensor([[3],[2],[1]])

tensor([[10]])

In [28]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

In [29]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [30]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [31]:
tensor_A @ tensor_B

RuntimeError: ignored

In [32]:
tensor_A @ tensor_B.T

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [33]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
x.dtype

torch.int64

In [35]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [36]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [37]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [38]:
torch.argmax(tensor).item()

8

In [39]:
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [40]:
x.reshape((1,7)).shape

torch.Size([1, 7])

In [41]:
x.reshape((7,1)).shape

torch.Size([7, 1])

We can also change the view with torch.view()

Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

So changing the view changes the original tensor too.

In [42]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) 
x , x_stacked

(tensor([1., 2., 3., 4., 5., 6., 7.]), tensor([[1., 2., 3., 4., 5., 6., 7.],
         [1., 2., 3., 4., 5., 6., 7.],
         [1., 2., 3., 4., 5., 6., 7.],
         [1., 2., 3., 4., 5., 6., 7.]]))

In [43]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [44]:
print(f"Previous tensor: {x.reshape((1,7))}")
print(f"Previous shape: {x.reshape((1,7)).shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x.reshape((1,7)).squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [45]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


In [46]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [47]:
x_original.shape

torch.Size([224, 224, 3])

Note: Because permuting returns a view (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the original.

In [48]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.4660, 0.6845, 0.9571, 0.8619],
        [0.4132, 0.1004, 0.0861, 0.5241],
        [0.6560, 0.5954, 0.5835, 0.3857]])

Tensor B:
tensor([[0.6039, 0.5232, 0.0304, 0.3296],
        [0.4448, 0.1968, 0.5128, 0.4546],
        [0.7888, 0.1772, 0.4888, 0.1641]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [49]:

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [50]:
!nvidia-smi

Mon Mar  6 09:39:03 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P0    25W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [52]:
# Check for GPU
# You can test if PyTorch has access to a GPU using torch.cuda.is_available().
torch.cuda.is_available()

True

Now, let's say you wanted to setup your code so it ran on CPU or the GPU if it was available.

That way, if you or someone decides to run your code, it'll work regardless of the computing device they're using.

Let's create a device variable to store what kind of device is available.

In [54]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [55]:
# Count number of gpu devices
torch.cuda.device_count()

1

In [56]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [57]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: ignored

In [58]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [59]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [64]:
# Create a random tensor with shape (7, 7)

tensor1 = torch.rand(size=(7,7))
tensor

tensor([[0.9998, 0.5944, 0.6541, 0.0337, 0.1716, 0.3336, 0.5782],
        [0.0600, 0.2846, 0.2007, 0.5014, 0.3139, 0.4654, 0.1612],
        [0.1568, 0.2083, 0.3289, 0.1054, 0.9192, 0.4008, 0.9302],
        [0.6558, 0.0766, 0.8460, 0.3624, 0.3083, 0.0850, 0.0029],
        [0.6431, 0.3908, 0.6947, 0.0897, 0.8712, 0.1330, 0.4137],
        [0.6044, 0.7581, 0.9037, 0.9555, 0.1035, 0.6258, 0.2849],
        [0.4452, 0.1258, 0.9554, 0.1330, 0.7672, 0.6757, 0.6625]])

In [66]:
tensor2 = torch.rand(size=(1,7))
tensor2

tensor([[0.9837, 0.5723, 0.3705, 0.7069, 0.3096, 0.1764, 0.8649]])

In [68]:
tensor1 @ tensor2.T

tensor([[1.9082],
        [2.0173],
        [1.0920],
        [2.4508],
        [2.1692],
        [1.5301],
        [1.5715]])

In [71]:
torch.manual_seed(seed=1234)
tensor1 = torch.rand(size=(7,7))
torch.manual_seed(seed=1234)
tensor2 = torch.rand(size=(1,7))
tensor1 @ tensor2.T

tensor([[0.8613],
        [1.2761],
        [1.1540],
        [1.0134],
        [0.6783],
        [1.1122],
        [0.7266]])

In [74]:
torch.manual_seed(seed=1234)
tensor1 = torch.rand(size=(7,7))
torch.manual_seed(seed=1234)
tensor2 = torch.rand(size=(1,7))
tensor1 @ tensor2.T

tensor([[0.8613],
        [1.2761],
        [1.1540],
        [1.0134],
        [0.6783],
        [1.1122],
        [0.7266]])

In [75]:
torch.manual_seed(seed=1234)
tensor1 = torch.rand(size=(7,7),device="cuda")
torch.manual_seed(seed=1234)
tensor2 = torch.rand(size=(1,7),device="cuda")
tensor1 @ tensor2.T

tensor([[2.5893],
        [2.1242],
        [1.8872],
        [2.5468],
        [1.7516],
        [1.6445],
        [1.6517]], device='cuda:0')

In [76]:
torch.manual_seed(seed=1234)
tensor1 = torch.rand(size=(7,7),device="cuda")
torch.manual_seed(seed=1234)
tensor2 = torch.rand(size=(1,7),device="cuda")
tensor1 @ tensor2.T

tensor([[2.5893],
        [2.1242],
        [1.8872],
        [2.5468],
        [1.7516],
        [1.6445],
        [1.6517]], device='cuda:0')

In [77]:
w = torch.empty(3,5)
w

tensor([[0.0000e+00, 0.0000e+00, 7.7052e+31, 7.2148e+22, 1.5766e-19],
        [1.0256e-08, 4.1019e-08, 3.1300e+12, 6.7735e-10, 1.7092e-04],
        [1.0861e-05, 1.2962e+16, 2.1707e-18, 7.0952e+22, 1.7748e+28]])

In [79]:
torch.cuda.manual_seed(seed=1230)
tensor1 = torch.rand(size=(7,7),device="cuda")
torch.cuda.manual_seed(seed=1230)
tensor2 = torch.rand(size=(1,7),device="cuda")
tensor1 @ tensor2.T

tensor([[2.3527],
        [1.4642],
        [2.2041],
        [2.1282],
        [1.4328],
        [2.4887],
        [0.9514]], device='cuda:0')

In [82]:
torch.cuda.manual_seed(seed=1230)
tensor1 = torch.rand(size=(7,7),device="cuda")
torch.cuda.manual_seed(seed=1230)
tensor2 = torch.rand(size=(1,7),device="cuda")
tensor1 @ tensor2.T


tensor([[2.3527],
        [1.4642],
        [2.2041],
        [2.1282],
        [1.4328],
        [2.4887],
        [0.9514]], device='cuda:0')

In [83]:
t = tensor1 @ tensor2.T
t.max()

tensor(2.4887, device='cuda:0')

In [85]:
t.min()

tensor(0.9514, device='cuda:0')

In [91]:
t1 = torch.rand((1, 3, 2, 10))

In [92]:
t1,t1.shape

(tensor([[[[0.7837, 0.5631, 0.7749, 0.8208, 0.2793, 0.6817, 0.2837, 0.6567,
            0.2388, 0.7313],
           [0.6012, 0.3043, 0.2548, 0.6294, 0.9665, 0.7399, 0.4517, 0.4757,
            0.7842, 0.1525]],
 
          [[0.6662, 0.3343, 0.7893, 0.3216, 0.5247, 0.6688, 0.8436, 0.4265,
            0.9561, 0.0770],
           [0.4108, 0.0014, 0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655,
            0.8839, 0.8083]],
 
          [[0.7528, 0.8988, 0.6839, 0.7658, 0.9149, 0.3993, 0.1100, 0.2541,
            0.4333, 0.4451],
           [0.4966, 0.7865, 0.6604, 0.1303, 0.3498, 0.3824, 0.8043, 0.3186,
            0.2908, 0.4196]]]]), torch.Size([1, 3, 2, 10]))

In [93]:
t1.squeeze().shape

torch.Size([3, 2, 10])